PUT http://localhost:8080/telemetry
content-type:application/json

{
    "coordinate": { "x": 9, "y": 9, "z": 10 }, 
    "rotation": { "p": 1, "y": 2, "r": 3 },
    "fuel": 100,
    "temp": 50,
    "status": {"payloadPower": "ON", "dataWaiting": false, "chargeStatus": false, "voltage": 12.5}
}

###
PUT http://localhost:8080/telemetry
content-type:application/json

"{
    "coordinate": { "x": 9, "y": 9, "z": 10 }, 
    "rotation": { "p": 1, "y": 2, "r": 3 },
    "fuel": 100,
    "temp": 50,
    "status": {"payloadPower": "ON", "dataWaiting": false, "chargeStatus": false, "voltage": 12.5}
}"

###

GET http://localhost:8080/telemetry/

###

GET http://localhost:8080/styles/styles.css

###

GET http://localhost:8080/execute/testScriptName

####
// bad test do not test
PUT http://localhost:8080/receive?ID=5
content-type:application/json

{
    "verb":"GET",
    "uri":"http://localhost:8080/telemetry/",
    "data":"{}"
}

###

POST http://localhost:8080/receive?ID=5
content-type:application/json

{
    "verb":"GET",
    "uri":"http://localhost:8080/styles/styles.css",
    "data":{}
}

###


PUT http://localhost:8080/receive?ID=5 HTTP/1.1
content-type:application/json

{
    "verb":"PUT",
    "uri":"http://localhost:8081/telemetry",
    "data": "{\"coordinates\": { \"x\": \"8\", \"y\": \"9\", \"z\": \"10\" },\"rotations\": { \"p\": \"1\", \"y\": \"2\", \"r\": \"3\" },\"fuel\": \"100\",\"temp\": \"50\", \"status\": {\"payloadPower\": \"ON\", \"dataWaiting\": \"False\", \"chargeStatus\": \"False\", \"voltage\": \"12.5\"}}"
}

       
